# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-llama-error',
                'doc_host': 'https://franfram.github.io',
                'git_url': 'https://github.com/franfram/nbdev-llama-error',
                'lib_path': 'nbdev_llama_error'},
  'syms': {'nbdev_llama_error.core': {'nbdev_llama_error.core.foo': ('core.html#foo', 'nbdev_llama_error/core.py')}}}
